In [1]:
import pandas as pd
from ipynb.fs.full.utils import get_df, rename_values
from ipynb.fs.full.plots import single_barplot

In [2]:
df = get_df()

In [4]:
print(df)

      ID          Status Duration D1_Undergraduation  \
2     31  Completed (31)     1317          Economics
3     34  Completed (31)      854                -99
4     36  Completed (31)     1593        Mathematics
5     57  Completed (31)     4238   Computer Science
6     46  Completed (31)     2821  Actuarial Science
..   ...             ...      ...                ...
273  458  Suspended (22)        0   Computer Science
274  499  Suspended (22)        0   Computer Science
275  500  Suspended (22)        0   Computer Science
276  518  Suspended (22)        0   Computer Science
277  522  Suspended (22)       35                -99

                   D1_Specialization                        D1_Master  \
2                                -99               M.Sc. in Economics
3                        Management                                No
4                        Informatics             MSC Computer Science
5        Data science specialization                              -99
6    Post Graduation in Data Science  M Sc in Data Science -ML models
..                               ...                              ...
273             Software Engineering                 Computer Systems
274                              -99                              -99
275      Data Science Specialization        M.Sc. in Computer Science
276                              -99                              -99
277                              -99                              -99

                   D1_Phd                  D1_Courses D1_Others  \
2                     -99  Data Scientist in Datacamp       -99
3                      No                          No        No
4    PhD computer Science   VÃ¡rios cursos in Coursera       -99
5                     -99                         -99       -99
6                 no Ph D     no other certifications       -99
..                    ...                         ...       ...
273      Computer Science                        none       -99
274                   -99                         -99       -99
275                   -99                         -99       -99
276                   -99                         -99       -99
277                   -99                         -99       -99

         D2_Country  ... Q12_RE_Most_Difficult_Activity_AligningREData  \
2            Brazil  ...                                    not quoted
3            Brazil  ...                                    not quoted
4            Brazil  ...                                    not quoted
5           Germany  ...                                    not quoted
6            Brazil  ...                                    not quoted
..              ...  ...                                           ...
273  United Kingdom  ...                                           -77
274          Brazil  ...                                           -77
275          Brazil  ...                                           -77
276          Brazil  ...                                           -77
277               0  ...                                    not quoted

    Q12_RE_Most_Difficult_Activity_Conflicts   \
2                                      quoted
3                                  not quoted
4                                  not quoted
5                                  not quoted
6                                  not quoted
..                                        ...
273                                       -77
274                                       -77
275                                       -77
276                                       -77
277                                not quoted

    Q12_RE_Most_Difficult_Activity_NewQualityAttributes  \
2                                           not quoted
3                                           not quoted
4                                           not quoted
5                                               quoted
6                                           not quoted
..                                                 ...
273                                                -77
274                                                -77
275                                                -77
276                                                -77
277                                         not quoted

    Q12_RE_Most_Difficult_Activity_Documentation   \
2                                      not quoted
3                                      not quoted
4                                      not quoted
5                                          quoted
6                                      not quoted
..                                            ...
273                                           -77
274                                           -77
275                                           -77
276                                           -77
277                                    not quoted

    Q12_RE_Most_Difficult_Activity_SelectingMetrics  \
2                                        not quoted
3                                        not quoted
4                                            quoted
5                                        not quoted
6                                        not quoted
..                                              ...
273                                             -77
274                                             -77
275                                             -77
276                                             -77
277                                      not quoted

    Q12_RE_Most_Difficult_Activity_Verification   \
2                                     not quoted
3                                     not quoted
4                                     not quoted
5                                     not quoted
6                                     not quoted
..                                           ...
273                                          -77
274                                          -77
275                                          -77
276                                          -77
277                                   not quoted

    Q12_RE_Most_Difficult_Activity_ChangingRE   \
2                                   not quoted
3                                   not quoted
4                                   not quoted
5                                   not quoted
6                                   not quoted
..                                         ...
273                                        -77
274                                        -77
275                                        -77
276                                        -77
277                                 not quoted

    Q12_RE_Most_Difficult_Activity_Customer_Others  \
2                                       not quoted
3                                       not quoted
4                                       not quoted
5                                       not quoted
6                                       not quoted
..                                             ...
273                                            -77
274                                            -77
275                                            -77
276                                            -77
277                                     not quoted

    Q12_RE_Most_Difficult_Activity_Customer_Others_Free  \
2                                                  -99
3                                                  -99
4                                                  -99
5                                                  -99
6                                                  -99
..                                                 ...
273                                                -66
274                                                -66
275                                                -66
276                                                -66
277                                                -99

                                       Origin
2             https://ww2.unipark.de/uc/seml/
3                                         -99
4                                         -99
5                                         -99
6                                         -99
..                                        ...
273  https://machine-learning-survey.web.app/
274  https://machine-learning-survey.web.app/
275  https://machine-learning-survey.web.app/
276  https://machine-learning-survey.web.app/
277  https://machine-learning-survey.web.app/

[276 rows x 185 columns]

In [5]:
df[['Q13','Q13_1']]

KeyError: "None of [Index(['Q13', 'Q13_1'], dtype='object')] are in the [columns]"