In [7]:
import pandas as pd
from ipynb.fs.full.utils import custom_groupby, get_df, rename_values
from ipynb.fs.full.plots import heatmap

In [8]:
df = get_df()

In [9]:
df.head(10)

,ID,Status,Duration,D1_Undergraduation,D1_Specialization,D1_Master,D1_Phd,D1_Courses,D1_Others,D2_Country,...,Q15_Model_Deploy_Production_Monitoring,Q16_Model_Monitor_Aspects_Input_And_Output,Q16_Model_Monitor_Aspects_Interpretability_Output,Q16_Model_Monitor_Aspects_Output_And_Decisions,Q16_Model_Monitor_Aspects_Fairness,Q16_Model_Monitor_Aspects_Others,Q16_Model_Monitor_Aspects_Others_Free,Q17_Automated_Machine_Learning_Tools_Yes_No,Q17_Automated_Machine_Learning_Tools_Yes_Free,Origin
2,31,Completed (31),1317,Economics,-99,M.Sc. in Economics,-99,Data Scientist in Datacamp,-99,Brazil,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/
3,34,Completed (31),854,-99,Management,No,No,No,No,Brazil,...,70,not quoted,not quoted,quoted,not quoted,not quoted,-99,No,-99,-99
4,36,Completed (31),1593,Mathematics,Informatics,MSC Computer Science,PhD computer Science,VÃ¡rios cursos in Coursera,-99,Brazil,...,60,quoted,not quoted,quoted,not quoted,not quoted,-99,"Yes, Please, specify",Own approach,-99
5,57,Completed (31),4238,Computer Science,Data science specialization,-99,-99,-99,-99,Germany,...,100,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
6,46,Completed (31),2821,Actuarial Science,Post Graduation in Data Science,M Sc in Data Science -ML models,no Ph D,no other certifications,-99,Brazil,...,80,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
7,53,Completed (31),2097,Information System,-99,M.Sc. in Applied Informatics,-99,-99,-99,Brazil,...,30,quoted,quoted,not quoted,not quoted,not quoted,-99,No,-99,-99
8,58,Completed (31),1696,Computer Science,-99,Computer Science,-99,Microsoft Professional Program Data Science & ...,-99,Germany,...,10,quoted,not quoted,not quoted,not quoted,not quoted,-99,No,-99,https://t.co/
9,64,Completed (31),1250,Electrical and Electronics Engineering,-99,M.Sc. in AI and Software Engineering,Computer science,"Azure Associate AI Engineer, Azure Data Scienc...",-99,Sweden,...,0,not quoted,not quoted,not quoted,not quoted,not quoted,-99,No,-99,https://www.linkedin.com/
10,65,Completed (31),106,-99,-99,-99,-99,-99,-99,0,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,-99
11,69,Completed (31),79,-99,-99,-99,-99,-99,-99,0,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/

In [11]:
df[['D10_ML_Management_Framework_None', 'D10_ML_Management_Framework_CRISP-DM', 'D10_ML_Management_Framework_Kanban',
    'D10_ML_Management_Framework_Lean', 'D10_ML_Management_Framework_RUP', 'D10_ML_Management_Framework_SAFe',
    'D10_ML_Management_Framework_Scrum', 'D11_Agile_Development']].head()

,D10_ML_Management_Framework_None,D10_ML_Management_Framework_CRISP-DM,D10_ML_Management_Framework_Kanban,D10_ML_Management_Framework_Lean,D10_ML_Management_Framework_RUP,D10_ML_Management_Framework_SAFe,D10_ML_Management_Framework_Scrum,D11_Agile_Development
2,not quoted,not quoted,not quoted,not quoted,not quoted,not quoted,not quoted,Totally traditional
3,not quoted,not quoted,not quoted,not quoted,not quoted,not quoted,quoted,Balanced between agile and traditional
4,quoted,not quoted,not quoted,not quoted,not quoted,not quoted,not quoted,Balanced between agile and traditional
5,not quoted,not quoted,not quoted,not quoted,not quoted,not quoted,quoted,Totally agile
6,not quoted,not quoted,quoted,not quoted,not quoted,not quoted,not quoted,Balanced between agile and traditional

In [18]:
frameworks_mapping = {
    'D10_ML_Management_Framework_None': 'None',
    'D10_ML_Management_Framework_CRISP-DM': 'CRISP-DM',
    'D10_ML_Management_Framework_Kanban': 'Kanban',
    'D10_ML_Management_Framework_Lean': 'Lean',
    'D10_ML_Management_Framework_RUP': 'RUP',
    'D10_ML_Management_Framework_SAFe': 'SAFe',
    'D10_ML_Management_Framework_Scrum': 'Scrum'
}

In [22]:
frameworks = []
agility = []
framework_agility = []
for index, row in df.iterrows():
    for f in frameworks_mapping:
        # formatted name for framework
        frameworks.append(frameworks_mapping[f])
        # what did the guy who answered an specific framework about agility
        agility.append(row['D11_Agile_Development'])
        # match
        if row[f] == 'not quoted':
            framework_agility.append(0)
        elif row[f] == 'quoted':
            framework_agility.append(1)

In [23]:
# create a custom dataframe to handle only the columns that we want
d10_11_df = pd.DataFrame()
d10_11_df['Framework'] = frameworks
d10_11_df['Agility'] = agility
d10_11_df['Answers'] = framework_agility

In [35]:
d10_11_df.head(1900)

     Framework              Agility  Answers
0         None  Totally traditional        0
1     CRISP-DM  Totally traditional        0
2       Kanban  Totally traditional        0
3         Lean  Totally traditional        0
4          RUP  Totally traditional        0
...        ...                  ...      ...
1895      SAFe  Totally traditional        0
1896     Scrum  Totally traditional        0
1897      None  Totally traditional        1
1898  CRISP-DM  Totally traditional        0
1899    Kanban  Totally traditional        0

[1900 rows x 3 columns]

In [32]:
d10_11_df['Agility'].value_counts()

Mostly agile                              623
Balanced between agile and traditional    539
Totally traditional                       287
Mostly traditional                        203
Totally agile                             161
I don't know                              112
0                                           7
Name: Agility, dtype: int64

In [28]:
d10_11_df['Answers'].value_counts()

0    1575
1     357
Name: Answers, dtype: int64

In [42]:
d10_11_df.index.to_list()[1000:]

[1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1246,
 1247,
 1248,
 1249,
 1250,
 1251,
 1252,
 1253,
 1254,
 1255,
 1256,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1492,
 1493,
 1494,
 1495,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 1508,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 1519,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 1550,
 1551,
 1552,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1577,
 1578,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1604,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1613,
 1614,
 1615,
 1616,
 1617,
 1618,
 1619,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1669,
 1670,
 1671,
 1672,
 1673,
 1674,
 1675,
 1676,
 1677,
 1678,
 1679,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1687,
 1688,
 1689,
 1690,
 1691,
 1692,
 1693,
 1694,
 1695,
 1696,
 1697,
 1698,
 1699,
 1700,
 1701,
 1702,
 1703,
 1704,
 1705,
 1706,
 1707,
 1708,
 1709,
 1710,
 1711,
 1712,
 1713,
 1714,
 1715,
 1716,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1724,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1734,
 1735,
 1736,
 1737,
 1738,
 1739,
 1740,
 1741,
 1742,
 1743,
 1744,
 1745,
 1746,
 1747,
 1748,
 1749,
 1750,
 1751,
 1752,
 1753,
 1754,
 1755,
 1756,
 1757,
 1758,
 1759,
 1760,
 1761,
 1762,
 1763,
 1764,
 1765,
 1766,
 1767,
 1768,
 1769,
 1770,
 1771,
 1772,
 1773,
 1774,
 1775,
 1776,
 1777,
 1778,
 1779,
 1780,
 1781,
 1782,
 1783,
 1784,
 1785,
 1786,
 1787,
 1788,
 1789,
 1790,
 1791,
 1792,
 1793,
 1794,
 1795,
 1796,
 1797,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1805,
 1806,
 1807,
 1808,
 1809,
 1810,
 1811,
 1812,
 1813,
 1814,
 1815,
 1816,
 1817,
 1818,
 1819,
 1820,
 1821,
 1822,
 1823,
 1824,
 1825,
 1826,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1833,
 1834,
 1835,
 1836,
 1837,
 1838,
 1839,
 1840,
 1841,
 1842,
 1843,
 1844,
 1845,
 1846,
 1847,
 1848,
 1849,
 1850,
 1851,
 1852,
 1853,
 1854,
 1855,
 1856,
 1857,
 1858,
 1859,
 1860,
 1861,
 1862,
 1863,
 1864,
 1865,
 1866,
 1867,
 1868,
 1869,
 1870,
 1871,
 1872,
 1873,
 1874,
 1875,
 1876,
 1877,
 1878,
 1879,
 1880,
 1881,
 1882,
 1883,
 1884,
 1885,
 1886,
 1887,
 1888,
 1889,
 1890,
 1891,
 1892,
 1893,
 1894,
 1895,
 1896,
 1897,
 1898,
 1899,
 1900,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919,
 1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1930,
 1931]

In [43]:
heatmap(d10_11_df.set_index(['Framework', 'Agility', 'Answers'], append=True), 'Framework', 'Agility', 'Answers', title='Frameworks and Agility')

KeyError: 'Framework'

In [44]:
d10_11_df.set_index(['Framework', 'Agility', 'Answers'], append=True)

Empty DataFrame
Columns: []
Index: [(0, None, Totally traditional, 0), (1, CRISP-DM, Totally traditional, 0), (2, Kanban, Totally traditional, 0), (3, Lean, Totally traditional, 0), (4, RUP, Totally traditional, 0), (5, SAFe, Totally traditional, 0), (6, Scrum, Totally traditional, 0), (7, None, Balanced between agile and traditional, 0), (8, CRISP-DM, Balanced between agile and traditional, 0), (9, Kanban, Balanced between agile and traditional, 0), (10, Lean, Balanced between agile and traditional, 0), (11, RUP, Balanced between agile and traditional, 0), (12, SAFe, Balanced between agile and traditional, 0), (13, Scrum, Balanced between agile and traditional, 1), (14, None, Balanced between agile and traditional, 1), (15, CRISP-DM, Balanced between agile and traditional, 0), (16, Kanban, Balanced between agile and traditional, 0), (17, Lean, Balanced between agile and traditional, 0), (18, RUP, Balanced between agile and traditional, 0), (19, SAFe, Balanced between agile and traditional, 0), (20, Scrum, Balanced between agile and traditional, 0), (21, None, Totally agile, 0), (22, CRISP-DM, Totally agile, 0), (23, Kanban, Totally agile, 0), (24, Lean, Totally agile, 0), (25, RUP, Totally agile, 0), (26, SAFe, Totally agile, 0), (27, Scrum, Totally agile, 1), (28, None, Balanced between agile and traditional, 0), (29, CRISP-DM, Balanced between agile and traditional, 0), (30, Kanban, Balanced between agile and traditional, 1), (31, Lean, Balanced between agile and traditional, 0), (32, RUP, Balanced between agile and traditional, 0), (33, SAFe, Balanced between agile and traditional, 0), (34, Scrum, Balanced between agile and traditional, 0), (35, None, Balanced between agile and traditional, 0), (36, CRISP-DM, Balanced between agile and traditional, 0), (37, Kanban, Balanced between agile and traditional, 1), (38, Lean, Balanced between agile and traditional, 0), (39, RUP, Balanced between agile and traditional, 0), (40, SAFe, Balanced between agile and traditional, 0), (41, Scrum, Balanced between agile and traditional, 1), (42, None, Balanced between agile and traditional, 1), (43, CRISP-DM, Balanced between agile and traditional, 0), (44, Kanban, Balanced between agile and traditional, 0), (45, Lean, Balanced between agile and traditional, 0), (46, RUP, Balanced between agile and traditional, 0), (47, SAFe, Balanced between agile and traditional, 0), (48, Scrum, Balanced between agile and traditional, 1), (49, None, Mostly agile, 0), (50, CRISP-DM, Mostly agile, 0), (51, Kanban, Mostly agile, 1), (52, Lean, Mostly agile, 0), (53, RUP, Mostly agile, 0), (54, SAFe, Mostly agile, 0), (55, Scrum, Mostly agile, 0), (56, None, Totally traditional, 0), (57, CRISP-DM, Totally traditional, 0), (58, Kanban, Totally traditional, 0), (59, Lean, Totally traditional, 0), (60, RUP, Totally traditional, 0), (61, SAFe, Totally traditional, 0), (62, Scrum, Totally traditional, 0), (63, None, Totally traditional, 0), (64, CRISP-DM, Totally traditional, 0), (65, Kanban, Totally traditional, 0), (66, Lean, Totally traditional, 0), (67, RUP, Totally traditional, 0), (68, SAFe, Totally traditional, 0), (69, Scrum, Totally traditional, 0), (70, None, Balanced between agile and traditional, 0), (71, CRISP-DM, Balanced between agile and traditional, 0), (72, Kanban, Balanced between agile and traditional, 0), (73, Lean, Balanced between agile and traditional, 0), (74, RUP, Balanced between agile and traditional, 0), (75, SAFe, Balanced between agile and traditional, 0), (76, Scrum, Balanced between agile and traditional, 1), (77, None, Balanced between agile and traditional, 0), (78, CRISP-DM, Balanced between agile and traditional, 0), (79, Kanban, Balanced between agile and traditional, 1), (80, Lean, Balanced between agile and traditional, 0), (81, RUP, Balanced between agile and traditional, 0), (82, SAFe, Balanced between agile and traditional, 0), (83, Scrum, Balanced between agile and traditional, 1), (84, None, Totally traditional, 0), (85, CRISP-DM, Totally traditional, 0), (86, Kanban, Totally traditional, 0), (87, Lean, Totally traditional, 0), (88, RUP, Totally traditional, 0), (89, SAFe, Totally traditional, 0), (90, Scrum, Totally traditional, 0), (91, None, Mostly agile, 1), (92, CRISP-DM, Mostly agile, 0), (93, Kanban, Mostly agile, 0), (94, Lean, Mostly agile, 0), (95, RUP, Mostly agile, 0), (96, SAFe, Mostly agile, 0), (97, Scrum, Mostly agile, 0), (98, None, Totally traditional, 1), (99, CRISP-DM, Totally traditional, 0), ...]

[1932 rows x 0 columns]