# Question Q4: Practitioners Main Problems on Model Monitoring Stage

*Question*: According to your personal experience, please outline the main problems or difficulties (up to three) faced during each of the seven ML life cycle stages.

*Answer Type*: Text Free

### Necessary Libraries

In [1]:
import pandas as pd
from utils.basic import rename_values
from utils.dataframe import DataframeUtils
from utils.plot import PlotUtils
from utils.bootstrapping import BootstrappingUtils

### Dataframe Initialization

Here we get a formatted Pandas DataFrame from a raw CSV containing the Survey responses. When formatting, we discard unused columns and renames existing ones to more clear names. We created two classes that help us manage this dataframe and create meaningful charts.

In [2]:
dataframe_obj = DataframeUtils(df_path='./data/main_data.csv', sep=';',
                               to_discard_columns_file='./data/unused_columns.txt',
                               to_format_columns_file='./data/formatted_columns.txt')
# dataframe preview
dataframe_obj.df.head()

,ID,Status,Duration,D1_Undergraduation,D1_Specialization,D1_Master,D1_Phd,D1_Courses,D1_Others,D2_Country,...,Q15_Model_Deploy_Production_Monitoring,Q16_Model_Monitor_Aspects_Input_And_Output,Q16_Model_Monitor_Aspects_Interpretability_Output,Q16_Model_Monitor_Aspects_Output_And_Decisions,Q16_Model_Monitor_Aspects_Fairness,Q16_Model_Monitor_Aspects_Others,Q16_Model_Monitor_Aspects_Others_Free,Q17_Automated_Machine_Learning_Tools_Yes_No,Q17_Automated_Machine_Learning_Tools_Yes_Free,Origin
2,31,Completed (31),1317,Economics,-99,M.Sc. in Economics,-99,Data Scientist in Datacamp,-99,Brazil,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/
3,34,Completed (31),854,-99,Management,No,No,No,No,Brazil,...,70,not quoted,not quoted,quoted,not quoted,not quoted,-99,No,-99,-99
4,36,Completed (31),1593,Mathematics,Informatics,MSC Computer Science,PhD computer Science,Vários cursos in Coursera,-99,Brazil,...,60,quoted,not quoted,quoted,not quoted,not quoted,-99,"Yes, Please, specify",Own approach,-99
5,57,Completed (31),4238,Computer Science,Data science specialization,-99,-99,-99,-99,Germany,...,100,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
6,46,Completed (31),2821,Actuarial Science,Post Graduation in Data Science,M Sc in Data Science -ML models,no Ph D,no other certifications,-99,Brazil,...,80,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99

In this research, we conservatively considered those who fully completed the survey. So, we discarded suspended submissions.

In [3]:
dataframe_obj.df.drop(dataframe_obj.df[dataframe_obj.df['Status'] == 'Suspended (22)'].index, inplace = True)

In [4]:
# dataframe preview
dataframe_obj.df.head()

,ID,Status,Duration,D1_Undergraduation,D1_Specialization,D1_Master,D1_Phd,D1_Courses,D1_Others,D2_Country,...,Q15_Model_Deploy_Production_Monitoring,Q16_Model_Monitor_Aspects_Input_And_Output,Q16_Model_Monitor_Aspects_Interpretability_Output,Q16_Model_Monitor_Aspects_Output_And_Decisions,Q16_Model_Monitor_Aspects_Fairness,Q16_Model_Monitor_Aspects_Others,Q16_Model_Monitor_Aspects_Others_Free,Q17_Automated_Machine_Learning_Tools_Yes_No,Q17_Automated_Machine_Learning_Tools_Yes_Free,Origin
2,31,Completed (31),1317,Economics,-99,M.Sc. in Economics,-99,Data Scientist in Datacamp,-99,Brazil,...,-77,not quoted,not quoted,not quoted,not quoted,not quoted,-99,0,-99,https://ww2.unipark.de/uc/seml/
3,34,Completed (31),854,-99,Management,No,No,No,No,Brazil,...,70,not quoted,not quoted,quoted,not quoted,not quoted,-99,No,-99,-99
4,36,Completed (31),1593,Mathematics,Informatics,MSC Computer Science,PhD computer Science,Vários cursos in Coursera,-99,Brazil,...,60,quoted,not quoted,quoted,not quoted,not quoted,-99,"Yes, Please, specify",Own approach,-99
5,57,Completed (31),4238,Computer Science,Data science specialization,-99,-99,-99,-99,Germany,...,100,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99
6,46,Completed (31),2821,Actuarial Science,Post Graduation in Data Science,M Sc in Data Science -ML models,no Ph D,no other certifications,-99,Brazil,...,80,not quoted,quoted,quoted,not quoted,not quoted,-99,No,-99,-99

### Grounded Theory

Here we get a formatted Pandas DataFrame from an Excel file containing the codes and categorization of our qualitative responses.

In [5]:
qualitative_df = pd.read_excel('./data/Problems on ML Stages/MODEL MONITORING.xlsx')
qualitative_df.head()

,lfdn,MODEL MONITORING,TOPIC,CATEGORY
0,31,Verify the results,CHOOSE AND EVALUATE THE METRICS,METHOD
1,36,Assess metricts,CHOOSE AND EVALUATE THE METRICS,METHOD
2,46,"after deploy, data have the same ML results as...",CHOOSE AND EVALUATE THE METRICS,METHOD
3,64,Determine what metrics to monitor,CHOOSE AND EVALUATE THE METRICS,METHOD
4,72,Monitoring a model of another person (that u d...,LACK OF MODEL KNOWLEDGE,METHOD

### Basic Analysis

In [6]:
# get our valid respondents ids
respondents_ids = list(dataframe_obj.df['ID'])
respondents_ids = [int(respondent_id) for respondent_id in respondents_ids]
respondents_ids[:5]

[31, 34, 36, 57, 46]

In [7]:
# discard the ids that are suspended
qualitative_df = qualitative_df[qualitative_df['lfdn'].isin(respondents_ids)][['MODEL MONITORING', 'TOPIC', 'CATEGORY']]

In [8]:
# get a list with all the reported categories
category_column = list(qualitative_df['CATEGORY'])
category_column[:5]

['METHOD', 'METHOD', 'METHOD', 'METHOD', 'METHOD']

In [9]:
# compute the total of answers that belong to each category
total_per_category_df = qualitative_df[['CATEGORY', 'TOPIC']].groupby(['CATEGORY']).count()
total_per_category_df

                TOPIC
CATEGORY
DATA                5
INFRASTRUCTURE     35
INPUT               4
METHOD             56
ORGANIZATION        5
PEOPLE              7

In [10]:
# get the total of qualitative answers
total_answers = total_per_category_df['TOPIC'].sum()
print(f'The total of qualitative answers to be considered is {total_answers}')

The total of qualitative answers to be considered is 112

In [11]:
# we create two lists that contain, for each category, the total of qualitative answers and their percentage
category_percentage = []
category_total = []
# note that we will have repeated values, once we are creating lists with the same length of the column 'CATEGORY' in the qualitative dataframe
for category in category_column:
    category_percentage.append(round(total_per_category_df.loc[category]['TOPIC'] / total_answers * 100, 2))
    category_total.append(total_per_category_df.loc[category]['TOPIC'])

In [12]:
# include two new columns to our qualitative dataframe
qualitative_df['CATEGORY_TOTAL'] = category_total
qualitative_df['CATEGORY_%'] = category_percentage
qualitative_df.head()

,MODEL MONITORING,TOPIC,CATEGORY,CATEGORY_TOTAL,CATEGORY_%
0,Verify the results,CHOOSE AND EVALUATE THE METRICS,METHOD,56,50.0
1,Assess metricts,CHOOSE AND EVALUATE THE METRICS,METHOD,56,50.0
2,"after deploy, data have the same ML results as...",CHOOSE AND EVALUATE THE METRICS,METHOD,56,50.0
3,Determine what metrics to monitor,CHOOSE AND EVALUATE THE METRICS,METHOD,56,50.0
4,Monitoring a model of another person (that u d...,LACK OF MODEL KNOWLEDGE,METHOD,56,50.0

In [13]:
# now we group our results considering the category and the topic
qualitative_df = qualitative_df.groupby(['CATEGORY', 'CATEGORY_TOTAL', 'CATEGORY_%', 'TOPIC']).count()

In [14]:
# rename the remaining column, which is now a simple count representing the quantity of each category and topic
qualitative_df.columns = ['QUANTITY']
# add the percentage version of each quantity to improve readability
qualitative_df['QUANTITY_%'] = round(qualitative_df['QUANTITY'] / qualitative_df['QUANTITY'].sum() * 100, 2)
qualitative_df

                                                                                         QUANTITY  \
CATEGORY       CATEGORY_TOTAL CATEGORY_% TOPIC
DATA           5              4.46       DATA ACCESSIBILITY                                     1
                                         DATA QUALITY                                           2
                                         HOW TO SPLIT THE DATASET                               1
                                         INSUFFICIENT DATA                                      1
INFRASTRUCTURE 35             31.25      ARCHITECTURE                                           1
                                         COMPUTATIONAL CONSTRAINTS                              3
                                         DEVELOP TOOLS TO MONITOR                              26
                                         DYNAMIC ENVIRONMENT - NEED TO UPDATE THE MODEL         3
                                         INFRASTRUCTURE                                         1
                                         VERSION CONTROL                                        1
INPUT          4              3.57       LACK OF DOMAIN KNOWLEDGE                               3
                                         SCOPE CREEP                                            1
METHOD         56             50.00      BASELINE FOR COMPARISON                                1
                                         CHOOSE AND EVALUATE THE METRICS                       18
                                         COMPARISON                                             1
                                         CRITERIA FOR RETRAINING                                1
                                         DRIFTS                                                 2
                                         EVALUATE PERFORMANCE                                   2
                                         FAILURE DETECTION                                      1
                                         FAULT HANDLING                                         1
                                         IMPROVING THE MODEL                                    2
                                         INTERPRET RESULTS CORRECTLY                            1
                                         LACK OF MODEL KNOWLEDGE                                1
                                         LACK OF MONITORING INTERFACES                          3
                                         LIVE FEEDBACK                                          5
                                         MODEL IMPROVEMENT                                      3
                                         MODEL UNDERSTANDING                                    1
                                         MODEL UPDATE                                           3
                                         NO MODEL MONITORING PRACTICE IN PLACE                  7
                                         ONLINE ISSUES                                          1
                                         PROGRAMMING LANGUAGE                                   1
                                         UI                                                     1
ORGANIZATION   5              4.46       LACK OF PRIORITIZATION                                 2
                                         LACK OF PRODUCTION SUPPORT                             1
                                         LACK OF TIME                                           2
PEOPLE         7              6.25       LACK OF DATA SCIENCE KNOWLEDGE                         1
                                         LACK OF PATIENCE                                       1
                                         LACK OF TALENT/SKILL                                   5

                                                                                         QUANTITY_%
CATEGORY       CATEGORY_TOTAL CATEGORY_% TOPIC
DATA           5              4.46       DATA ACCESSIBILITY                                    0.89
                                         DATA QUALITY                                          1.79
                                         HOW TO SPLIT THE DATASET                              0.89
                                         INSUFFICIENT DATA                                     0.89
INFRASTRUCTURE 35             31.25      ARCHITECTURE                                          0.89
                                         COMPUTATIONAL CONSTRAINTS                             2.68
                                         DEVELOP TOOLS TO MONITOR                             23.21
                                         DYNAMIC ENVIRONMENT - NEED TO UPDATE THE MODEL        2.68
                                         INFRASTRUCTURE                                        0.89
                                         VERSION CONTROL                                       0.89
INPUT          4              3.57       LACK OF DOMAIN KNOWLEDGE                              2.68
                                         SCOPE CREEP                                           0.89
METHOD         56             50.00      BASELINE FOR COMPARISON                               0.89
                                         CHOOSE AND EVALUATE THE METRICS                      16.07
                                         COMPARISON                                            0.89
                                         CRITERIA FOR RETRAINING                               0.89
                                         DRIFTS                                                1.79
                                         EVALUATE PERFORMANCE                                  1.79
                                         FAILURE DETECTION                                     0.89
                                         FAULT HANDLING                                        0.89
                                         IMPROVING THE MODEL                                   1.79
                                         INTERPRET RESULTS CORRECTLY                           0.89
                                         LACK OF MODEL KNOWLEDGE                               0.89
                                         LACK OF MONITORING INTERFACES                         2.68
                                         LIVE FEEDBACK                                         4.46
                                         MODEL IMPROVEMENT                                     2.68
                                         MODEL UNDERSTANDING                                   0.89
                                         MODEL UPDATE                                          2.68
                                         NO MODEL MONITORING PRACTICE IN PLACE                 6.25
                                         ONLINE ISSUES                                         0.89
                                         PROGRAMMING LANGUAGE                                  0.89
                                         UI                                                    0.89
ORGANIZATION   5              4.46       LACK OF PRIORITIZATION                                1.79
                                         LACK OF PRODUCTION SUPPORT                            0.89
                                         LACK OF TIME                                          1.79
PEOPLE         7              6.25       LACK OF DATA SCIENCE KNOWLEDGE                        0.89
                                         LACK OF PATIENCE                                      0.89
                                         LACK OF TALENT/SKILL                                  4.46